name:                opengl-playground
version:             0.1.0.0
github:              "githubuser/haskell-opengl"
license:             BSD3
author:              "Jan Sipr"
maintainer:          "sipr.jan@gmail.com"
copyright:           "2018 Jan Sipr"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-opengl#readme>

dependencies:
  - base >= 4.7 && < 5
  - attoparsec
  - bytestring
  - containers
  - GLFW-b
  - JuicyPixels
  - lens
  - OpenGL
  - ObjectName
  - OpenGLRaw
  - parser-combinators
  - pretty-simple
  - StateVar
  - text
  - transformers
  - vector
  - dimensions
  - easytensor
  - filepath

library:
  source-dirs: src

executables:
  play:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - opengl-playground

tests:
  opengl-playground:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - opengl-playground
