version: "3.9"

services:
  bash-log-gen:
    build:
      dockerfile: Dockerfile
      target: bash-log-gen
    depends_on:
      - opentelemetry-collector
    restart: always
    logging:
      driver: syslog
      options:
        syslog-format: rfc5424
        syslog-address: tcp://127.0.0.1:54526

  opentelemetry-collector:
    image:  otel/opentelemetry-collector-contrib:0.54.0
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    command: [ "--config=/etc/otel-collector-config.yml" ]
    depends_on:
      - loki
    ports:
      - "127.0.0.1:54526:54526"

  loki:
    image: grafana/loki:2.4.1
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
      - loki-data:/loki/
    user: "10001:10001"

  grafana:
    image: grafana/grafana:9.0.2
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana-provisioning/:/etc/grafana/provisioning
    depends_on:
      - loki
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

volumes:
  loki-data:
