receivers:
  syslog:
    tcp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc5424
    location: UTC
    operators:
      - type: json_parser
        parse_from: attributes.message
      - type: time_parser
        parse_from: attributes.timestamp
        layout: '%Y-%m-%dT%H:%M:%S.%LZ'
      - type: severity_parser
        parse_from: attributes.severity_text
        mapping:
      - type: move
        from: attributes.body
        to: body
      - type: remove
        field: attributes.timestamp
      - type: remove
        field: attributes.message
      - type: remove
        field: attributes.severity_text
      - type: add
        field: attributes.application
        value: "bash_logger"

exporters:
  logging:
  #    loglevel: debug

  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    format: json
    labels:
      attributes:
        application: ""

extensions:
  health_check:
    check_collector_pipeline:
      enabled: false
      interval: "5m"
      exporter_failure_threshold: 5

service:
  extensions: [health_check]
    #  telemetry:
    #    logs:
    #      level: "debug"
  pipelines:
    logs:
      receivers: [syslog]
      processors: []
      exporters: [loki, logging]
