version: "3.9"

services:
  bash-log-gen:
    build:
      dockerfile: Dockerfile
      target: bash-log-gen
    depends_on:
      fluent:
        condition: service_healthy
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-address: 127.0.0.1:24224

  fluent:
    build:
      dockerfile: Dockerfile
      target: fluent
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    links:
      - "elasticsearch"
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
      - "127.0.0.1:5140:5140"
      - "9800:9800"
    restart: always
    healthcheck:
      test: curl -f http://localhost:9800/
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  elasticsearch:
    image: elasticsearch:8.2.3
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    environment:
      discovery.type: "single-node"
      ELASTIC_PASSWORD: "password"
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false

  kibana:
    image: kibana:8.2.3
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
